### PR TITLE
Implement FromStr and TryFrom traits for UriBuf and UriRefBuf

### LINKED ISSUE #22: Implement more traits for UriRefBuf and UriBuf
The following traits could be implemented
- [`FromStr`](https://doc.rust-lang.org/std/str/trait.FromStr.html)
- [`TryFrom`](https://doc.rust-lang.org/std/convert/trait.TryFrom.html)
-> `TryFrom<&str>`
-> `TryFrom<&String>`
-> `TryFrom<String>` (only for `UriBuf`)
-> `impl<T: AsRef<UriRef>> TryFrom<T>`

Most of these traits can be simply delegated to their respective function

```rust
use std::str::FromStr;

impl FromStr for UriBuf {
   type Err = ParseError;

    fn from_str(input: &str) -> Result<Self, Self::Err> { Self::from_str(input) }
}
```

### PR DESCRIPTION
**Pull request by Luro02**
Closes #22 

I also fixed a broken doc link :)

### CODE REVIEW

**Comment by Luro02** [comment]
@googlebot I signed it!

**Comment by darconeous** [comment]
Not sure why travis isn't running. Looking into it.

**Comment by darconeous** [comment]
Commit 257cd4e looks useful, but would likely be better suited in a separate pull request.

**Comment by darconeous** [comment]
The first 5 commits look good. I will merge them in manually today. I'll have a closer look at 257cd4e after I review your other PRs.

**Comment by darconeous** [comment]
Note that merge commit 99a61ee does not include 257cd4e. Please file a new PR for that.

**Pull request closed without merging**
